trigger:
  branches:
    include:
      - '*'

jobs:
- job: GitsecretsCheck
  displayName: 'Gitsecrets Check'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      sudo apt-get update
      sudo apt-get install -y wget
      wget https://github.com/awslabs/git-secrets/archive/1.3.0.tar.gz
      tar -xvf 1.3.0.tar.gz
      cd git-secrets-1.3.0
      sudo make install
    displayName: 'Install Gitsecrets'

  - script: |
      git secrets --register-aws --global
      git secrets --install
      git secrets --scan --recursive
    displayName: 'Run Gitsecrets Scan'
